# Full reference
# https://book.getfoundry.sh/reference/config/

[profile.default]
# This is the last version safe for chains that haven't adopted to the Shangai hardfork EVM changes.
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 20000
gas_reports = ["*"]
via_ir = false

# allow all paths — necessary for pnpm
allow_paths = ["/"]

[profile.ci]
# Gives super verbose output by default (-vvvv) when running tests on CI.
verbosity = 4
